# ... di .github/workflows/android_release_build.yml

    - name: Build Signed App Bundle via make.sh
      run: ./make.sh bundleRelease 

    - name: Upload Signed AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Signed-Release-AAB
        # PERBAIKAN: Menggunakan wildcard untuk menemukan AAB di folder rilis
        path: app/build/outputs/bundle/release/**/*.aab 
        retention-days: 7
