# ... (Di dalam bagian 'steps:')

    # Hapus atau ganti langkah yang menghasilkan Debug APK (seperti yang ditunjukkan di log Anda)
    # - name: Build Debug APK via make.sh
    #   run: ./make.sh # Atau perintah yang menghasilkan Debug

    - name: Build Signed Android App Bundle (AAB)
      # Gunakan perintah Gradle yang BENAR untuk membuat App Bundle RILIS yang sudah ditandatangani.
      run: ./gradlew bundleRelease 
      # Pastikan file gradlew berada di root proyek Anda.
      
    - name: Upload Signed AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Signed-Release-AAB
        path: app/build/outputs/bundle/release/app-release.aab
        retention-days: 7

# ...
