# ... di .github/workflows/android_release_build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Kredensial Keystore dari GitHub Secrets
    env:
      STORE_FILE: ${{ secrets.MYAPP_RELEASE_STORE_FILE }} # <-- Gunakan nama Secret yang baru
      KEY_ALIAS: ${{ secrets.MYAPP_RELEASE_KEY_ALIAS }}
      STORE_PASS: ${{ secrets.MYAPP_RELEASE_STORE_PASSWORD }}
      KEY_PASS: ${{ secrets.MYAPP_RELEASE_KEY_PASSWORD }}

    steps:
      # ... langkah-langkah lainnya

      - name: Inject Keystore Properties
        run: |
          # Perhatikan: Nama properti di sini HARUS sama dengan yang ada di build.gradle
          echo "MYAPP_RELEASE_STORE_FILE=${{ env.STORE_FILE }}" > app/keystore.properties
          echo "MYAPP_RELEASE_STORE_PASSWORD=${{ env.STORE_PASS }}" >> app/keystore.properties
          echo "MYAPP_RELEASE_KEY_ALIAS=${{ env.KEY_ALIAS }}" >> app/keystore.properties
          echo "MYAPP_RELEASE_KEY_PASSWORD=${{ env.KEY_PASS }}" >> app/keystore.properties

      # ... langkah-langkah selanjutnya
