# File: .github/workflows/android_release_build.yml

name: Build dan Sign AAB Rilis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      # Kode checkout secara default menempatkan file di root working directory.

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'

    - name: Install dependencies
      # Perintah ini HARUS dijalankan dari root proyek (tempat pubspec.yaml berada)
      run: flutter pub get 

    # --- Menyuntikkan Kredensial Keystore ke Gradle Properti ---
    - name: Inject Keystore Properties
      # Perintah ini menargetkan android/app/gradle.properties, 
      # jadi kita harus memastikan path-nya benar dari root proyek.
      run: |
        echo "KEYSTORE_FILE=${{ env.KEYSTORE_FILE }}" >> android/app/gradle.properties
        echo "KEYSTORE_PASSWORD=${{ env.KEYSTORE_PASSWORD }}" >> android/app/gradle.properties
        echo "KEY_ALIAS=${{ env.KEY_ALIAS }}" >> android/app/gradle.properties
        echo "KEY_PASSWORD=${{ env.KEY_PASSWORD }}" >> android/app/gradle.properties

    - name: Build Signed Android App Bundle (AAB)
      # Perintah ini HARUS dijalankan dari root proyek.
      run: flutter build appbundle --release

    - name: Upload Signed AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Signed-Release-AAB
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 7
