# File: .github/workflows/android_release_build.yml

name: Build dan Sign AAB Rilis (Native Android)

on:
  push:
    branches:
      - master # Sesuaikan dengan branch utama Anda
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # HAPUS BLOK ENV SEPENUHNYA! Kita akan gunakan secrets langsung di bawah.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Inject Keystore Properties
      # PERBAIKAN KRUSIAL: Menyuntikkan Secrets langsung ke file keystore.properties.
      run: |
        echo "MYAPP_RELEASE_STORE_FILE=${{ secrets.MYAPP_RELEASE_STORE_FILE }}" > app/keystore.properties
        echo "MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.MYAPP_RELEASE_STORE_PASSWORD }}" >> app/keystore.properties
        echo "MYAPP_RELEASE_KEY_ALIAS=${{ secrets.MYAPP_RELEASE_KEY_ALIAS }}" >> app/keystore.properties
        echo "MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.MYAPP_RELEASE_KEY_PASSWORD }}" >> app/keystore.properties
        
    - name: Grant Execute Permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Signed Android App Bundle (AAB)
      # PERBAIKAN KRUSIAL: Menjalankan bundleRelease
      run: ./gradlew bundleRelease
      
    - name: Upload Signed AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Signed-Release-AAB
        path: app/build/outputs/bundle/release/app-release.aab 
        retention-days: 7
